name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }},
      NODE_ENV: ${{ secrets.NODE_ENV }},
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }},
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }},
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }},
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }},
      NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
